// Generates sw.js (offline cache) from the files that actually exist, so the list never drifts.
// Run after every change to the app files:  node tools/build_sw.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import crypto from 'node:crypto';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const include = ['index.html', 'config.js', 'manifest.webmanifest', 'css', 'js', 'vendor', 'icons'];
const files = [];
const walk = (p) => {
  const abs = path.join(root, p);
  if (fs.statSync(abs).isDirectory()) fs.readdirSync(abs).sort().forEach(f => walk(path.join(p, f)));
  else files.push(p.split(path.sep).join('/'));
};
include.forEach(walk);

const hash = crypto.createHash('sha256');
for (const f of files) { hash.update(f); hash.update(fs.readFileSync(path.join(root, f))); }
const version = hash.digest('hex').slice(0, 12);

const sw = `/* Generated by tools/build_sw.mjs — do not edit by hand. */
const VERSION = '${version}';
const CACHE = 'mri-app-' + VERSION;
const PRECACHE = ${JSON.stringify(['./', ...files], null, 1)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('mri-app-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;   // Google / Drive calls are never cached
  if (req.mode === 'navigate') {
    // newest index.html when online, cached copy when offline
    event.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('./', copy)); return res; })
      .catch(() => caches.match('./')));
    return;
  }
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  })));
});
`;
fs.writeFileSync(path.join(root, 'sw.js'), sw);
console.log(`sw.js written: version ${version}, ${files.length + 1} precached files`);
