/*
 * MRI Personal Workspace — User Guide.
 * One source of truth: the same content becomes the PDF that is uploaded to
 * the user's Google Drive and the docs/PANDUAN-PENGGUNA.md file
 * (generated by tools/build_docs.mjs).
 */
import { getJsPDF } from './vendor.js';
import { pdfSafe } from './reports.js';
import { CONFIG } from '../config.js';

export const GUIDE = [
  { h: 'Apa itu MRI Personal Workspace?', p: [
    'MRI adalah ruang kerja rekrutmen pribadi untuk seorang HR. Semua data (kandidat, CV, lowongan, hasil screening, keputusan, karyawan) disimpan di browser Anda sendiri — bukan di server penjual. Google Drive Anda dipakai untuk backup, template, panduan, SOP, dan file yang ingin dibagikan.',
    'AI di MRI bersifat rule-based (tanpa biaya API, tanpa internet). AI hanya memberi ekstraksi, skor, bukti, dan rekomendasi; keputusan akhir selalu Anda yang mengambil.' ] },
  { h: 'Langkah pertama', p: [
    '1. Buka alamat aplikasi di Chrome, Edge, Firefox, atau Safari versi terbaru.',
    '2. Isi nama Anda dan nama workspace. Nama Anda akan tercatat sebagai reviewer pada setiap keputusan.',
    '3. Aplikasi berjalan di paket Demo (gratis). Coba dulu lewat tombol "Load Demo Data" di Executive Dashboard.',
    '4. Sangat disarankan: langsung lakukan backup pertama di menu "Data & Backup", lalu aktifkan penyimpanan persisten bila diminta browser.' ] },
  { h: 'Alur kerja harian', p: [
    'a. Job Requirement (menu 06): buat lowongan beserta kriteria dan bobot — atau mulai dari template di Knowledge Center.',
    'b. CV Intake (menu 02): unggah CV satuan, banyak file, atau satu folder (PDF/DOCX/TXT, maks. 8 MB per file). Sistem membaca profil kandidat dan menandai duplikat (file sama, email sama, atau no. HP sama).',
    'c. Screening Center (menu 03): pilih lowongan, klik "Screen Semua Kandidat CV Bank", buka baris kandidat untuk melihat skor per kriteria, bukti, kriteria yang terpenuhi/belum, lalu ambil keputusan: Pass, Talent Pool, Hold, atau Reject.',
    'd. Candidate 360 (menu 04): riwayat lengkap satu kandidat, catat hasil tahap wawancara/assessment/offering/medical/hired.',
    'e. Talent Pool (menu 05): kandidat yang disimpan untuk kebutuhan mendatang; "Re-match" ke lowongan baru kapan saja.',
    'f. Employee Data Center (menu 09): setelah kandidat mencapai tahap HIRED, buat data karyawan; atau impor karyawan yang sudah ada lewat template Excel.' ] },
  { h: 'Catatan penting tentang skor AI', p: [
    'Skor dihitung dari pendidikan, pengalaman, keahlian teknis, soft skill, kepemimpinan, dan sertifikasi yang terdeteksi di CV terhadap kriteria lowongan. CV hasil scan/foto tanpa lapisan teks tidak bisa dibaca (OCR belum didukung).',
    'Kriteria tambahan (usia, domisili, dll.) hanya catatan untuk Anda tinjau manual dan tidak dinilai AI. Hindari kriteria berbasis agama, ras, atau suku tanpa dasar kualifikasi pekerjaan yang sah (UU Ketenagakerjaan Pasal 5-6).' ] },
  { h: 'Backup, restore, dan pindah perangkat', p: [
    'Data ada di browser di perangkat ini. Jika data browser dihapus atau perangkat rusak, data ikut hilang — karena itu backup rutin wajib.',
    'Backup: menu "Data & Backup" → "Unduh Backup". File .zip berisi seluruh data (dan file CV asli jika dipilih). Simpan di tempat aman atau kirim ke Google Drive.',
    'Pindah perangkat: (1) di perangkat lama, buat backup; (2) di perangkat baru buka aplikasi, pilih "Pulihkan dari file backup" pada layar awal (atau menu Data & Backup); (3) pilih file .zip — seluruh workspace, termasuk lisensi, kembali seperti semula.',
    'Memulihkan backup MENGGANTI seluruh data di perangkat tersebut. Aplikasi meminta konfirmasi terlebih dulu.' ] },
  { h: 'Google Drive', p: [
    'Menu "Google Drive": klik "Sambungkan Google Drive" dan izinkan akses. MRI hanya meminta akses ke file yang dibuatnya sendiri (scope drive.file) — file lain di Drive Anda tidak terlihat oleh MRI.',
    'MRI membuat folder "MRI Workspace" berisi: 1 Panduan, 2 Template Excel, 3 Backup Data, 4 Manual & SOP, 5 File Distribusi.',
    'Yang bisa dilakukan: simpan backup ke Drive dan pulihkan dari Drive; unggah Panduan dan Template Excel; unggah manual/SOP atau file distribusi; salin otomatis laporan yang Anda ekspor ke folder File Distribusi lalu bagikan lewat tautan Drive.' ] },
  { h: 'Paket dan lisensi', p: [
    'Demo (gratis): 15 kandidat nyata, 3 lowongan, tanpa ekspor laporan. Premium: 500 kandidat, 50 lowongan, ekspor Excel/PDF. VIP: tanpa batas.',
    'Upgrade: menu "Paket & Upgrade" → tempel kode aktivasi dari penjual (atau unggah file .lic/.txt). Kode diverifikasi di perangkat Anda tanpa internet. Lisensi ikut tersimpan di backup.' ] },
  { h: 'Privasi', p: [
    'Data kandidat tidak dikirim ke server MRI. Data hanya berpindah jika Anda sendiri mengunduh backup, mengekspor laporan, atau menyambungkan Google Drive Anda.',
    'Gunakan perangkat pribadi/terkunci untuk data rekrutmen, dan jangan berbagi file backup sembarangan — isinya data pribadi kandidat.' ] },
  { h: 'Pemecahan masalah', p: [
    'CV ditolak "tidak ada teks": file adalah hasil scan. Unggah versi PDF/DOCX asli.',
    'PDF terproteksi password: buka proteksinya lalu unggah ulang.',
    'Batas paket Demo tercapai: aktifkan kode Premium/VIP, atau hapus data demo dari Executive Dashboard.',
    'Tab lain sedang membuka MRI: tutup tab lain — hanya satu tab yang boleh membuka workspace pada satu waktu agar data tidak bentrok.',
    'Google Drive gagal tersambung: izinkan pop-up untuk situs ini, dan pastikan Client ID sudah diisi (lihat halaman Google Drive).' ] },
];

export function guideMarkdown() {
  const out = [`# Panduan Pengguna — ${CONFIG.APP_NAME}`, '', `Versi aplikasi ${CONFIG.APP_VERSION}`, ''];
  for (const s of GUIDE) { out.push(`## ${s.h}`, ''); for (const p of s.p) out.push(p, ''); }
  return out.join('\n');
}

export async function buildGuidePdf() {
  const jsPDF = await getJsPDF();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = doc.internal.pageSize.getWidth(), H = doc.internal.pageSize.getHeight();
  const M = 20, maxW = W - 2 * M;
  let y = 24;
  const ensure = (need) => { if (y + need > H - 18) { doc.addPage(); y = 22; } };

  doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.text('Panduan Pengguna', M, y); y += 8;
  doc.setFontSize(11); doc.setFont('helvetica', 'normal'); doc.text(pdfSafe(CONFIG.APP_NAME), M, y); y += 5;
  doc.setFontSize(9); doc.setTextColor(120); doc.text(`Versi aplikasi ${CONFIG.APP_VERSION}`, M, y); doc.setTextColor(0); y += 10;

  for (const s of GUIDE) {
    ensure(14);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.text(pdfSafe(s.h), M, y); y += 7;
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    for (const para of s.p) {
      const lines = doc.splitTextToSize(pdfSafe(para), maxW);
      for (const ln of lines) { ensure(5); doc.text(ln, M, y); y += 4.8; }
      y += 2;
    }
    y += 3;
  }
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i); doc.setFontSize(8); doc.setTextColor(128); doc.setFont('helvetica', 'italic');
    doc.text('Powered by Megay Studio', W / 2, H - 10, { align: 'center' });
    doc.text(`Halaman ${i} / ${pages}`, W - M, H - 10, { align: 'right' });
  }
  return new Uint8Array(doc.output('arraybuffer'));
}
