/* Generated by tools/build_sw.mjs — do not edit by hand. */
const VERSION = 'ff61cb60a382';
const CACHE = 'mri-app-' + VERSION;
const PRECACHE = [
 "./",
 "index.html",
 "config.js",
 "manifest.webmanifest",
 "css/style.css",
 "js/app.js",
 "js/backup.js",
 "js/core.js",
 "js/db.js",
 "js/demo.js",
 "js/drive.js",
 "js/engine.js",
 "js/extract.js",
 "js/guide.js",
 "js/license.js",
 "js/reports.js",
 "js/services.js",
 "js/svc_employees.js",
 "js/svc_knowledge.js",
 "js/svc_master.js",
 "js/svc_recruitment.js",
 "js/svc_system.js",
 "js/util.js",
 "js/vendor.js",
 "vendor/LICENSES.md",
 "vendor/exceljs.min.js",
 "vendor/fonts/ibm-plex-mono-latin-500-normal.woff2",
 "vendor/fonts/ibm-plex-mono-latin-600-normal.woff2",
 "vendor/fonts/inter-latin-400-normal.woff2",
 "vendor/fonts/inter-latin-500-normal.woff2",
 "vendor/fonts/inter-latin-600-normal.woff2",
 "vendor/fonts/inter-latin-700-normal.woff2",
 "vendor/fonts/space-grotesk-latin-500-normal.woff2",
 "vendor/fonts/space-grotesk-latin-600-normal.woff2",
 "vendor/fonts/space-grotesk-latin-700-normal.woff2",
 "vendor/jspdf.plugin.autotable.min.js",
 "vendor/jspdf.umd.min.js",
 "vendor/jszip.min.js",
 "vendor/nacl-fast.min.js",
 "vendor/pdfjs/pdf.min.mjs",
 "vendor/pdfjs/pdf.worker.min.mjs",
 "icons/icon.svg"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('mri-app-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;   // Google / Drive calls are never cached
  if (req.mode === 'navigate') {
    // newest index.html when online, cached copy when offline
    event.respondWith(fetch(req).then((res) => { const copy = res.clone(); caches.open(CACHE).then((c) => c.put('./', copy)); return res; })
      .catch(() => caches.match('./')));
    return;
  }
  event.respondWith(caches.match(req).then((hit) => hit || fetch(req).then((res) => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
    return res;
  })));
});
